version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
    - SMI/reviewers
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  reviewers:
    - SMI/reviewers
